In [1]:
from keyword import kwlist
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [3]:
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [5]:
p=print('hi')
print(p)

hi
None


In [9]:
print('''hi 
      I 
       am ''')

hi 
      I 
       am 


In [10]:
a='A sample python statement'
a[:-9]

'A sample python '

In [14]:
a[-11:-17:-1]

'nohtyp'

In [16]:
a[-1:-10:-1]

'tnemetats'

In [21]:
d={'a': 34 ,'b': 43,'c':23,'e':[1,2,6]}
d['e'][2]

6

In [27]:
d1=[{'a':34},66,{'66':[{'00':[98,'hi']},'awesome',{'m':'n'}]}]
d1[1]


66

In [29]:
d1[2]["66"][1]

'awesome'

In [27]:
s='468hi3.4'
a=[4,6,8,'hi',3.4]
b=(4,6,8,'hi',3.4)
c={4:6,8:['hi',3.4]}
d={4,6,8,'hi',3.4}

In [28]:
s=s[:3]+'jobhiaapchahe'+s[3:]
s

'468jobhiaapchahehi3.4'

In [43]:
#concatenation
a=a[:1]+['himani']+a[1:]
a
a+=['bye']

# assignment and deletion is possible in only mutable types
## ITEM ASSIGNMENT
 # s[0]='A' #not possiblr
#a[0]='A' #done
#b[0]='A' #not possible
#c[0]=66 #done

## item deletion
# del s[0] #not possible
#del a[0] #done
#del b[0] #not possible
#del c[0] #done

In [48]:
# anything non-zero or non-empty is true
print(bool(" "),bool([]),bool({}),bool(()),bool(-1),bool(45),bool([()]))


True False False False True True True


In [45]:
bool('False')

True

In [30]:
m=('bye')
type(m)
m=('bye',)
type(m)


tuple

In [31]:
b=b[:1]+('bye',)+b[1:]
b

(4, 'bye', 6, 8, 'hi', 3.4)

In [32]:
b+=('hello',)
b

(4, 'bye', 6, 8, 'hi', 3.4, 'hello')

In [33]:
(*a,*b,*c) #coverted into tuple #kwargs,args

(4, 'himani', 6, 8, 'hi', 3.4, 'bye', 4, 'bye', 6, 8, 'hi', 3.4, 'hello', 4, 8)

In [39]:
c

{4: 6, 8: ['hi', 3.4]}

In [40]:
c[99]=[86,'ekValue']
c

{4: 6, 8: ['hi', 3.4], 99: [86, 'ekValue']}

In [41]:
c2={'a':45,'b':35}
print(c)
print(c2)

{4: 6, 8: ['hi', 3.4], 99: [86, 'ekValue']}
{'a': 45, 'b': 35}


In [42]:
{**c,**c2}

{4: 6, 8: ['hi', 3.4], 99: [86, 'ekValue'], 'a': 45, 'b': 35}

In [34]:
type(s),type(a),type(b),type(c),type(d)

(str, list, tuple, dict, set)

In [35]:
len(s),len(a),len(b),len(c),len(d)

(21, 7, 7, 2, 5)

### concatenation
"hi"+"hello"

In [36]:
### concatenation
"hi"+"hello"

'hihello'

In [37]:
[4,5]+[2.3]


[4, 5, 2.3]

In [38]:
s +='k'
s

'468jobhiaapchahehi3.4k'

In [2]:
a=34
b=34.5
c=34+5j
d='hello'
e=[3,4,5]
f=(3,4,5)
g={3:[4,5]}
h={3,4,5}

In [52]:
d=d.upper()


### data type built-in functions
### str:upper,lower,find,split,strip,join,format,count,replace
### list:append,sort,count,copy,insert,remove,index,pop
### tuple:count,index
### dict: keys,values,update,get,pop
### set: add,difference,union,pop,remove

In [2]:
d.strip()

'hello'

In [3]:
d.strip('ohl')

'e'

In [4]:
'STAR'.join('wars')

'wSTARaSTARrSTARs'

In [10]:
'-'.join('himnai')
'#'.join('hi i am HImani'.split())


'hi#i#am#HImani'

In [9]:
'hi I am himani'.replace(' ','#')

'hi#I#am#himani'

In [12]:
d.count('l')

2

In [16]:
#string Formatting
x=20
y=30
# (Format Specifiers)-- Depricated
z='Ek aisa data jo %d to %d hai'%(x,y)
z
# using format function
z='Ek aisa data jo {} to {} hai'
z=z.format(x,y)
z

'Ek aisa data jo 20 to 30 hai'

In [18]:
z='Ek aisa data jo {} to {} hai'.format(x,y)
z

'Ek aisa data jo 20 to 30 hai'

In [22]:
z1='Ek aisa data jo {0} to {1} h lekin {0} hi kafi h'
z1=z1.format(x,y)
z1

'Ek aisa data jo 20 to 30 h lekin 20 hi kafi h'

In [23]:
# using f-string
zf=f'Ek aisa number jo {x} to {y} hai lekin {x} hi kafi h'
zf

'Ek aisa number jo 20 to 30 hai lekin 20 hi kafi h'

1. NO Inut and no output args
2. input arg but no output args
3. no input but output args are there
4. both are there

a. In -place( self update)
b. Non-in Place()

In [3]:
e.sort()
e


[3, 4, 5]

In [8]:
e.sort(reverse=True)
e

[5, 4, 3]

In [11]:
e1=['hi','hello','wow','yes','good','awesome']
e1.sort()
e1

['awesome', 'good', 'hello', 'hi', 'wow', 'yes']

In [13]:
e1.sort(key=len)
e1

['hi', 'wow', 'yes', 'good', 'hello', 'awesome']

In [15]:
f1=list(e1)
f1.sort(reverse=True)
f1

['yes', 'wow', 'hi', 'hello', 'good', 'awesome']

In [16]:
tuple(sorted(f1,reverse=True))

('yes', 'wow', 'hi', 'hello', 'good', 'awesome')

In [17]:
g.keys()

dict_keys([3])

In [19]:
type(g.keys())

dict_keys

In [20]:
g

{3: [4, 5]}

In [21]:
g['a']=44
g

{3: [4, 5], 'a': 44}

In [22]:
list(g.keys())[0]

3

In [24]:
g.get('a')

44

In [23]:
g.get('Z',"OH NO")

'OH NO'

In [25]:
g.get('Z','papa')

'papa'

In [26]:
e

[5, 4, 3]

In [28]:
e3=e
e3

[5, 4, 3]

In [30]:
e3.append(50)
e3

[5, 4, 3, 50, 50]

In [31]:
e #changes in e3 copied into e too

[5, 4, 3, 50, 50]

### Deep copy Vs Shallow copy

In [34]:
e4=e.copy()
e4

[5, 4, 3, 50, 50]

In [38]:
p=[3,4,5,7,3,9,1,45,22,11,5,2,4]
p1=set(p)
p1 #sorted set

{1, 2, 3, 4, 5, 7, 9, 11, 22, 45}

In [39]:
# Actual Programming
# Logics
#1.conditions
#2.Loops
#3.errors
#4.Functions
#5.classes
#6.library
 
#error handling
   #try-except-else-finally

#user defined  functions
   #def


In [44]:
a=21
while(a> 0):
    print('hello',a)
    a-=3
    if(a==11):
        break
    if(a<10):
        continue
    print('one more')
else:    
    print("Achaaa")

hello 21
one more
hello 18
one more
hello 15
one more
hello 12
hello 9
hello 6
hello 3
Achaaa


### Day5

In [1]:
a=[4,'hi','nice',35]
b=[]
for value in a:
    b.append(value*2)
b

[8, 'hihi', 'nicenice', 70]

In [2]:
# Comprehension
## for-loop which are one liner
# list comprehension
   #   [output -for loop]
   # [output-for loop if -condition]-Filtering of dataa
# dictionary comprehension
   #  { key_op:value_op for loop}
    #{output-for loop if -condition}-Filtering of dataa
# Set comprehension
   #{output for-loop}
   #{output-for loop if -condition}-Filtering of dataa
# GENERAtor comprehension
   # (output for loop)
b=[val*3 for val in a]
b

[12, 'hihihi', 'nicenicenice', 105]

In [19]:
k=[4,7,3,67,34,2,4,45,22,11,9,8]

In [4]:
p=[val for val in k if val%2==0] # only one if condition
p 

[4, 34, 2, 4, 22, 8]

In [6]:
p=[val for val in k if(val%2!=0) and val>10]
p

[67, 45, 11]

In [8]:
p=[val for val in k if not(val%2!=0) and val>10]
p

[34, 22]

In [10]:
#k=[]
#koi_function([val for val in k])
# donr for memory optimisation


In [23]:
# a>5?ye kar dena: nahi to ye vla krna
# ye kar dena if-cond elsse ye vla karna

# Task: mply by 2if odd ow check if it id less then 20 then do // ow do nthng
p=[val*2 if val %2==1 else(val //20 if (val <20) else val)for val in k]
p

[0, 14, 6, 134, 34, 0, 0, 90, 22, 22, 18, 0]

In [24]:
p=[val*2 if val %2==1 else val//2 for val in k]
p

[2, 14, 6, 134, 17, 1, 2, 90, 11, 22, 18, 4]

In [25]:
k


[4, 7, 3, 67, 34, 2, 4, 45, 22, 11, 9, 8]

In [26]:
m={val: val**2 for val in k if val%2==0}
m

{4: 16, 34: 1156, 2: 4, 22: 484, 8: 64}

In [27]:
for i in m:
    print(i)#key values

4
34
2
22
8


In [32]:
for i in m.items():
    print(i)

(4, 16)
(34, 1156)
(2, 4)
(22, 484)
(8, 64)


In [33]:
for i,j in m.items():
    print(i,j)

4 16
34 1156
2 4
22 484
8 64


In [36]:
def ekor(ekvalue,dusrivalue):
    print('kucj bhi')
    return ekvalue*dusrivalue

In [37]:
ekor(10,5)

kucj bhi


50

In [44]:
def merimarji(a,b):
    print('hi')
    return (a*b)+a

In [49]:
merimarji(b=10,a=3) #named parameter

hi


33

In [48]:
merimarji(10,b=3) #unnamed parameter always in left and named in right

hi


40

In [50]:
def merimarji(a,b=10): # default values always in right
    print('hi')
    return (a*b)+a

In [51]:
merimarji(1)

hi


11

In [55]:
def kuchor(*v):
    return v
kuchor(10)

(10,)

In [58]:
def kuchor(x=10,*v):
    return [i*x for i in v]
kuchor(3,6)

[18]

In [60]:
def kuchkuch(x=10,*v,**u):
    return[i*x for i in v],u
kuchkuch(3,6,8)

([18, 24], {})

In [61]:
kuchkuch(3,6,8,somedata=[3,4,5,6]) #dictionary

([18, 24], {'somedata': [3, 4, 5, 6]})

### day 6
### anonyms function(jiska koi nam ni h)
# python functions can be:
# 1. Assigned as a value
#2 taken as input argument in another function

#3 defined inside another function
#4 return a function as output from another function
 


In [5]:
def him():
    print('himani')

In [14]:
k='himani'
him()

himani


In [15]:
def abc(him):
    him()
abc(him='xyz')

TypeError: 'str' object is not callable

In [20]:
def pqr():
    def qrp():
        print('hello')
    qrp()
pqr()    

hello


In [18]:
def pqr():
    def qrp():
        print('hello')
    return qrp
x=pqr()
x
x()

hello


In [21]:
# Annonymous function-Lambda expressions
#Lambda inp_args : output(return)
#Its always one-liner
#always returns
#input arguments can be multiple,optional,keyword,nameed etc.
#output can be simple/conditional/comprehension etc.

In [22]:
def doubler(x):
    return x*2
m=doubler(34)
print(m)

68


In [27]:
doubler_L=lambda x : x*2
doubler_L

<function __main__.<lambda>(x)>

In [28]:
doubler_L(34)

68

In [29]:
oddeve=lambda x:'Odd' if x%2 else 'Even'
oddeve(45)

'Odd'

In [30]:
# scope of variable
#1. global
#2. local
#3. non local

In [33]:
x=10
def abc():
    x=30
    print(x)
abc()
print(x)    

30
10


In [36]:
x=10
def abc():
    global x
    x=30
print(x)
abc()
print(x)    

10
30


In [39]:
x=10
def abc():
    x=30
    y=15
    def xyz():
        y=28
        print('From xyz',x)
    xyz()
    print(y)
print(x)
abc()    
print(x)    

10
From xyz 30
15
10


In [42]:
x=10
def abc():
    x=30
    y=15
    def xyz():
        nonlocal y
        y=28
        print('From xyz',x)
    xyz()
    print(y)
print(x)
abc()    
print(x)

10
From xyz 30
28
10


In [2]:
import numpy

### Day 7

import first_program

In [3]:
import first_program

himani
20


In [4]:
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [5]:
from keyword import kwlist,iskeyword as isk
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [6]:
import numpy as np

In [7]:
c=np.array([[2,3,4],[3,4,5],[7,8,9],[4,5,7]])
c

array([[2, 3, 4],
       [3, 4, 5],
       [7, 8, 9],
       [4, 5, 7]])

In [9]:
c.shape


(4, 3)

In [10]:
d=np.array([[[2,20],[3,30],[4,40]],
            [[4,40],[5,50],[6,60]],
            [[7,70],[8,80],[9,90]],
            [[10,100],[11,110],[9,90]]])

In [11]:
d.shape

(4, 3, 2)

In [13]:
c.sum(axis=1)


array([ 9, 12, 24, 16])

In [14]:
c[0]

array([2, 3, 4])

In [15]:
c[0][1]

3

In [16]:
c[0:2,-1]

array([4, 5])

In [17]:
c[0:2,-1:]

array([[4],
       [5]])