In [2]:
import numpy as np


In [4]:
a=np.array([8,6,5])
a

array([8, 6, 5])

In [29]:
k=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k


array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [16]:
m=np.array([[[4,41],[8,81],[7,71]],
             [[3,31],[1,11],[5,51]],
             [[6,61],[9,91],[13,131]]])
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [17]:
m.shape


(3, 3, 2)

In [13]:
k.shape

(4, 3)

In [20]:
k[1,:]


array([9, 3, 5])

In [22]:
k[0:4:1,2] # showing row vise

array([ 4,  5, 17,  8])

In [33]:
k[:,2:3] # showing column vise using indexing

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [30]:
k[:,2:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [32]:
k[:,-1:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [36]:
m [1:3,1:3,0:1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [39]:
m [1:3,1:3,-2:-1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [40]:
m[1:3,0:1,0:2]

array([[[ 3, 31]],

       [[ 6, 61]]])

In [42]:

k+5

array([[ 8, 13,  9],
       [14,  8, 10],
       [16, 20, 22],
       [24, 36, 13]])

In [43]:
h=np.array([[1,2,3],[67,8,7],[5,6,7],[14,55,2]])
h

array([[ 1,  2,  3],
       [67,  8,  7],
       [ 5,  6,  7],
       [14, 55,  2]])

In [48]:
#modifying array elements
h[:,1]=[10,20,30,40]
h

array([[ 1, 10,  3],
       [67, 20,  7],
       [ 5, 30,  7],
       [14, 40,  2]])

In [50]:
h[0:2,1 :3]=[[100,200],[300,400]]
h

array([[  1, 100, 200],
       [ 67, 300, 400],
       [  5,  30,   7],
       [ 14,  40,   2]])

In [51]:
# add a new row(axis=0)
np.append(k,[[1,1,1]],axis=0)  # k not updating


array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8],
       [ 1,  1,  1]])

In [57]:
#add a new column (axis=1)
np.append(k,[[2],[4],[6],[7]],axis=1)

array([[ 3,  8,  4,  2],
       [ 9,  3,  5,  4],
       [11, 15, 17,  6],
       [19, 31,  8,  7]])

In [58]:
#deleting a row along with column
np.delete(k,1,1)

array([[ 3,  4],
       [ 9,  5],
       [11, 17],
       [19,  8]])

In [60]:
np.delete(k,3,axis=0) #3 row deleted

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17]])

In [61]:
k.shape

(4, 3)

In [62]:
k.reshape(6,2) #returned not replaced


array([[ 3,  8],
       [ 4,  9],
       [ 3,  5],
       [11, 15],
       [17, 19],
       [31,  8]])

In [63]:
k.astype

<function ndarray.astype>

In [64]:
k.dtype

dtype('int32')

In [65]:
a1=np.array([3.5,6,7,4.4])
a1

array([3.5, 6. , 7. , 4.4])

In [66]:
a1.dtype

dtype('float64')

In [69]:
a1.astype('uint16') #uint-unsingned integer

array([3, 6, 7, 4], dtype=uint16)

In [72]:
k.sum(axis=0)

array([42, 57, 34])

In [73]:
k.sum()

133

In [74]:
k.std(axis=1)

array([2.1602469 , 2.49443826, 2.49443826, 9.39266854])

In [75]:
#Nutshell
#we create arrays
#1 np.array()
#2.np.zeros()
#3 np.ones()
#4 np.arange()
#5 np.linspace()
#6. np.random.randint()

In [76]:
np.arange(1,11,1) #gap

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
np.random.randint(1,15,[3,4])

array([[ 4,  8,  1,  4],
       [13,  7, 13,  3],
       [10,  8, 14,  7]])

In [6]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
a*5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [11]:
np.zeros((1,2),dtype=int) 

array([[0, 0]])

In [12]:
np.linspace(1,10,10) #no of values we  want to generate

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
list(range(1,11,1)) #range works only on int value

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
np.random.randint(1,6,[1,3]) #dimensions of array-2d array

array([[5, 1, 5]])

In [20]:
np.random.randint(1,6,[2,2,2]) #3d array

array([[[5, 3],
        [5, 5]],

       [[2, 5],
        [2, 2]]])

In [23]:
# to save randomness
np.random.seed(10)
np.random.randint(31,6000,[4,3],)

array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [24]:
np.random.rand(3,4) #generate numbers btw 0.0 to 1.0

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [26]:
h=np.loadtxt('somedata.txt',dtype=str)
h

array(['hi', 'I', 'am', 'a', 'file', 'outside', 'the', 'jupyter', 'file'],
      dtype='<U7')

In [28]:
r=np.loadtxt('moredata.txt')
r

array([[45., 34., 22., 11., 89.],
       [44., 11., 90., 11.,  2.]])

In [34]:
p=np.random.rand(3,3)
p

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [35]:
np.savetxt('new.txt',p,delimiter=',')
# a new file 'new.txt' created and data got saved into it.